/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerLaundry;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelLaundry;
import util.Koneksi;

/**
 *
 * @author ChairulHamni
 */
public class ViewLaundry extends javax.swing.JFrame {
    Koneksi koneksi = new Koneksi();
    ControllerLaundry cl = new ControllerLaundry();
    ModelLaundry ml = new ModelLaundry();

    /**
     * Creates new form ViewLaundry
     */
    int Berat,harga,total;
    
    public ViewLaundry() {
        initComponents();
        dataTable();
        setLocationRelativeTo(null);
    }
    
    private void baru(){
        jButton1Baru.setEnabled(false);
        jButton2Simpan.setEnabled(true);
        jButton3Ubah.setEnabled(true);
        jButton4Hapus.setEnabled(true);
        jTextField2Nama.setEnabled(true);
        jTextField3Alamat.setEnabled(true);
        jTextField4JP.setEnabled(true);
        jTextField5Berat.setEnabled(true);
        jTextField6Harga.setEnabled(true);
        jTextField7Total.setEnabled(true);
    }
    
    private void bersih(){
        jTextField1.setText("");
        jTextField2Nama.setText("");
        jTextField3Alamat.setText("");
        jTextField4JP.setText("");
        jTextField5Berat.setText("");
        jTextField6Harga.setText("");
        jTextField7Total.setText("");
        jTextField2Nama.requestFocus();
   }
    
    private void dataTable(){
        koneksi.koneksiDatabase();
        
        DefaultTableModel tabel = new DefaultTableModel();
        
        tabel.addColumn("id");
        tabel.addColumn("nama");
        tabel.addColumn("alamat");
        tabel.addColumn("jenispakalian");
        tabel.addColumn("berat");
        tabel.addColumn("harga");
        tabel.addColumn("total");
        
        jTable1.setModel(tabel);
        try {
            String sql = "select * from tbl_pelanggan";
            
            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()){
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("alamat"),
                    res.getString("jenispakaian"),
                    res.getString("berat"),
                    res.getString("harga"),
                    res.getString("total"),
                });
                jTable1.setModel(tabel);
            }
        } catch (SQLException eer) {
            System.err.println("SQLException : "+eer.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField5Berat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6Harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7Total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3Alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4JP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1Baru = new javax.swing.JButton();
        jButton2Simpan = new javax.swing.JButton();
        jButton3Ubah = new javax.swing.JButton();
        jButton4Hapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setText("Harga :");

        jTextField6Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6HargaKeyReleased(evt);
            }
        });

        jLabel7.setText("Total :");

        jLabel1.setText("ID :");

        jLabel2.setText("Nama :");

        jLabel3.setText("Alamat :");

        jLabel4.setText("JenisPakaian :");

        jLabel5.setText("Berat/KG :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setForeground(new java.awt.Color(255, 51, 102));

        jButton1Baru.setText("Baru");
        jButton1Baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BaruActionPerformed(evt);
            }
        });

        jButton2Simpan.setText("Simpan");
        jButton2Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SimpanActionPerformed(evt);
            }
        });

        jButton3Ubah.setText("Ubah");
        jButton3Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3UbahActionPerformed(evt);
            }
        });

        jButton4Hapus.setText("Hapus");
        jButton4Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1Baru, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3Ubah)
                .addGap(31, 31, 31)
                .addComponent(jButton4Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Baru)
                    .addComponent(jButton2Simpan)
                    .addComponent(jButton3Ubah)
                    .addComponent(jButton4Hapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jLabel8.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Anggi Laundry");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(183, 183, 183))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7Total, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4JP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5Berat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5Berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SimpanActionPerformed
        // TODO add your handling code here:
        ControllerLaundry cl = new ControllerLaundry();
        ModelLaundry ml = new ModelLaundry();
        
        String Nama = jTextField2Nama.getText();
        String Alamat = jTextField3Alamat.getText();
        String JenisPakaian = jTextField4JP.getText();
        Berat = Integer.valueOf(jTextField5Berat.getText());
        harga = Integer.valueOf(jTextField6Harga.getText());
        total = Integer.valueOf(jTextField7Total.getText());
        
        try {
            ml.setNama(Nama);
            ml.setAlamat(Alamat);
            ml.setJenispakaian(JenisPakaian);
            ml.setBerat(Berat);
            ml.setHarga(harga);
            ml.setTotal(total);
            cl.simpanLaundry(ml);
            dataTable();
//            JOptionPokane.showMessageDialog(this, "berhasil disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "gagal disimpan");
            System.err.println(""+e);
        }
        
    }//GEN-LAST:event_jButton2SimpanActionPerformed

    private void jButton1BaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BaruActionPerformed
        // TODO add your handling code here:
        baru();
    }//GEN-LAST:event_jButton1BaruActionPerformed

    private void jButton3UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3UbahActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField1.getText());
            String nama = jTextField2Nama.getText();
            String alamat = jTextField3Alamat.getText();
            String jenispakaian = jTextField4JP.getText();
            int berat = Integer.valueOf(jTextField5Berat.getText());
            int Harga = Integer.valueOf(jTextField6Harga.getText());
            int Total = Integer.valueOf(jTextField7Total.getText());
            
            ml.setId(id);
            ml.setNama(nama);
            ml.setAlamat(alamat);
            ml.setJenispakaian(jenispakaian);
            ml.setBerat(berat);
            ml.setHarga(Harga);
            ml.setTotal(Total);
            
            cl.ubahData(ml);
            
            bersih();
            dataTable();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Masukan nama pelanggan");
        }
    }//GEN-LAST:event_jButton3UbahActionPerformed

    private void jButton4HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4HapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField1.getText());
            
            ml.setId(id);
            
            cl.hapusData(ml);
            dataTable();
            bersih();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Masukan nama pelanggan");
        }
    }//GEN-LAST:event_jButton4HapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        if(jTable1.getSelectedRowCount()==1){
            jTextField1.setText(jTable1.getValueAt(row, 0).toString());
            jTextField2Nama.setText(jTable1.getValueAt(row, 1).toString());
            jTextField3Alamat.setText(jTable1.getValueAt(row, 2).toString());
            jTextField4JP.setText(jTable1.getValueAt(row, 3).toString());
            jTextField5Berat.setText(jTable1.getValueAt(row, 4).toString());
            jTextField6Harga.setText(jTable1.getValueAt(row, 5).toString());
            jTextField7Total.setText(jTable1.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField6HargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6HargaKeyReleased
        // TODO add your handling code here:
        int berat,harga,total;
        try {
         berat = Integer.valueOf(jTextField5Berat.getText());
         harga = Integer.valueOf(jTextField6Harga.getText());
         
         total = berat * harga;
         
         jTextField7Total.setText(""+total);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ingat angka dan huruf itu berbeda");
        }
    }//GEN-LAST:event_jTextField6HargaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewLaundry().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Baru;
    private javax.swing.JButton jButton2Simpan;
    private javax.swing.JButton jButton3Ubah;
    private javax.swing.JButton jButton4Hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2Nama;
    private javax.swing.JTextField jTextField3Alamat;
    private javax.swing.JTextField jTextField4JP;
    private javax.swing.JTextField jTextField5Berat;
    private javax.swing.JTextField jTextField6Harga;
    private javax.swing.JTextField jTextField7Total;
    // End of variables declaration//GEN-END:variables
}
